[github]
organization = "MyHomeworkSpace"
repos = ["PlanBotTestRepo"]
privateKey = "./privatekey.pem"
appId = 99
installationId = 999999
ignoreLabels = ["waiting for details"]

[unassign]
daysUntilWarning = 5
daysUntilUnassign = 10

[slack]
token = "xoxb-something"
errlogChannel = "C260FU7HQ"

[users]
willbarkoff = "U0EGTKEFM"
thatoddmailbox = "U0EGDRXEK"
amazansky = "U0G281Q8L"